=== pypi-data/pypi-mirror-93/packages/beat.core/beat.core-1.13.2.zip/beat.core-1.13.2/beat/core/schema/toolchain/1.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Toolchain descriptor",
  "description": "This schema defines the properties of a toolchain",

  "type": "object",

  "properties": {

    "description": { "$ref": "../common/1.json#/definitions/description" },

    "datasets" : {
      "$ref": "common.json#/definitions/datasets"
    },

    "blocks": {
      "$ref": "common.json#/definitions/blocks"
    },

    "loops": {
      "type": "array",
      "uniqueItems": true,
      "items": { "$ref": "#/definitions/loop" }
    },

    "analyzers" : {
      "$ref": "common.json#/definitions/analyzers"
    },

    "connections" : {
      "$ref": "common.json#/definitions/connections"
    },

    "representation": {

      "type": "object",

      "properties": {

        "connections": {
          "$ref": "common.json#/definitions/representation/connection_list"
        },
        "blocks": {
          "$ref": "common.json#/definitions/representation/block_list"
        },
        "channel_colors": {
          "$ref": "common.json#/definitions/representation/channel_colors"
        }

      },

      "required": [
        "connections",
        "blocks",
        "channel_colors"
      ],

      "additionalProperties": false

    },

    "schema_version": { "$ref": "../common/1.json#/definitions/version" }

  },

  "required": [
    "datasets",
    "blocks",
    "analyzers",
    "connections",
    "representation"
  ],

  "additionalProperties": false
}

=== pypi-data/pypi-mirror-93/packages/beat.core/beat.core-1.13.2.zip/beat.core-1.13.2/beat/core/test/prefix/toolchains/user/integers_addition/3.json
{
    "connections": [
        {
            "to": "addition1.a",
            "from": "integers1.a",
            "channel": "integers1"
        },
        {
            "to": "addition1.b",
            "from": "integers1.b",
            "channel": "integers1"
        },
        {
            "to": "addition2.a",
            "from": "integers2.a",
            "channel": "integers2"
        },
        {
            "to": "addition2.b",
            "from": "integers2.b",
            "channel": "integers2"
        },
        {
            "to": "addition3.a",
            "from": "addition1.sum",
            "channel": "integers1"
        },
        {
            "to": "addition3.b",
            "from": "addition2.sum",
            "channel": "integers2"
        },
        {
            "to": "analysis.input",
            "from": "addition3.sum",
            "channel": "integers1"
        }
    ],
    "datasets": [
        {
            "outputs": [
                "a",
                "b"
            ],
            "name": "integers1"
        },
        {
            "outputs": [
                "a",
                "b"
            ],
            "name": "integers2"
        }
    ],
    "blocks": [
        {
            "inputs": [
                "a",
                "b"
            ],
            "synchronized_channel": "integers1",
            "name": "addition1",
            "outputs": [
                "sum"
            ]
        },
        {
            "inputs": [
                "a",
                "b"
            ],
            "synchronized_channel": "integers2",
            "name": "addition2",
            "outputs": [
                "sum"
            ]
        },
        {
            "inputs": [
                "a",
                "b"
            ],
            "synchronized_channel": "integers1",
            "name": "addition3",
            "outputs": [
                "sum"
            ]
        }
    ],
    "analyzers": [
        {
            "inputs": [
                "input"
            ],
            "synchronized_channel": "integers1",
            "name": "analysis"
        }
    ],
    "representation": {
      "connections": {
      },
      "blocks": {
      },
      "channel_colors": {
        "integers1": "#5555ff",
        "integers2": "#ff5555"
      }
    }
}

=== pypi-data/pypi-mirror-93/packages/beat.core/beat.core-1.13.1.zip/beat.core-1.13.1/beat/core/test/prefix/toolchains/user/double/1.json
{
  "connections": [
    {
      "to": "echo1.in",
      "from": "set.out",
      "channel": "set"
    },
    {
      "to": "echo2.in",
      "from": "echo1.out",
      "channel": "set"
    },
    {
      "to": "analysis.in",
      "from": "echo2.out",
      "channel": "set"
    }
  ],
  "analyzers": [
    {
      "inputs": [
        "in"
      ],
      "synchronized_channel": "set",
      "name": "analysis"
    }
  ],
  "datasets": [
    {
      "outputs": [
        "out"
      ],
      "name": "set"
    }
  ],
  "blocks": [
    {
      "inputs": [
        "in"
      ],
      "synchronized_channel": "set",
      "name": "echo1",
      "outputs": [
        "out"
      ]
    },
    {
      "inputs": [
        "in"
      ],
      "synchronized_channel": "set",
      "name": "echo2",
      "outputs": [
        "out"
      ]
    }
  ],
  "representation": {
    "connections": {
      "set.out/echo1.in": [
        {
          "col": 4,
          "row": 2
        },
        {
          "col": 5,
          "row": 2
        },
        {
          "col": 6,
          "row": 2
        },
        {
          "col": 7,
          "row": 2
        }
      ],
      "echo2.out/analysis.in": [
        {
          "col": 22,
          "row": 2
        },
        {
          "col": 23,
          "row": 2
        },
        {
          "col": 24,
          "row": 2
        },
        {
          "col": 25,
          "row": 2
        }
      ],
      "echo1.out/echo2.in": [
        {
          "col": 13,
          "row": 2
        },
        {
          "col": 14,
          "row": 2
        },
        {
          "col": 15,
          "row": 2
        },
        {
          "col": 16,
          "row": 2
        }
      ]
    },
    "blocks": {
      "set": {
        "width": 5,
        "height": 3,
        "col": -1,
        "row": 0
      },
      "analysis": {
        "width": 6,
        "height": 3,
        "col": 25,
        "row": 0
      },
      "echo2": {
        "width": 6,
        "height": 3,
        "col": 16,
        "row": 0
      },
      "echo1": {
        "width": 6,
        "height": 3,
        "col": 7,
        "row": 0
      }
    },
    "channel_colors": {
      "set": "#0000FF"
    }
  }
}

=== pypi-data/pypi-mirror-93/packages/beat.core/beat.core-1.13.3.zip/beat.core-1.13.3/beat/core/test/prefix/toolchains/user/integers_addition/1.json
{
    "connections": [
        {
            "from": "integers.a",
            "to": "addition.a",
            "channel": "integers"
        },
        {
            "from": "integers.b",
            "to": "addition.b",
            "channel": "integers"
        },
        {
            "from": "addition.sum",
            "to": "analysis.input",
            "channel": "integers"
        }
    ],
    "datasets": [
        {
            "outputs": [
                "a",
                "b"
            ],
            "name": "integers"
        }
    ],
    "blocks": [
        {
            "inputs": [
                "a",
                "b"
            ],
            "synchronized_channel": "integers",
            "name": "addition",
            "outputs": [
                "sum"
            ]
        }
    ],
    "analyzers": [
        {
            "inputs": [
                "input"
            ],
            "synchronized_channel": "integers",
            "name": "analysis"
        }
    ],
    "representation": {
      "connections": {
      },
      "blocks": {
      },
      "channel_colors": {
        "integers": "#5555ff"
      }
    }
}

=== pypi-data/pypi-mirror-93/packages/beat.core/beat.core-1.13.3.zip/beat.core-1.13.3/beat/core/test/prefix/toolchains/user/preprocessing/1.json
{
    "datasets": [
        {
            "outputs": [
                "a",
                "b"
            ],
            "name": "set"
        }
    ],
    "blocks": [
        {
            "name": "echo",
            "inputs": [
                "in"
            ],
            "outputs": [
                "out"
            ],
            "synchronized_channel": "set"
        },
        {
            "name": "add",
            "inputs": [
                "a",
                "b"
            ],
            "outputs": [
                "sum"
            ],
            "synchronized_channel": "set"
        }
    ],
    "analyzers": [
        {
            "name": "analysis",
            "inputs": [
                "in"
            ],
            "synchronized_channel": "set"
        }
    ],
    "connections": [
      {
          "from": "set.b",
          "to": "echo.in",
          "channel": "set"
      },
      {
          "from": "set.a",
          "to": "add.a",
          "channel": "set"
      },
      {
          "from": "echo.out",
          "to": "add.b",
          "channel": "set"
      },
      {
          "from": "add.sum",
          "to": "analysis.in",
          "channel": "set"
      }
    ],
    "representation": {
        "blocks": {
        },
        "connections": {
        },
        "channel_colors": {
        }
    }
}

=== pypi-data/pypi-mirror-93/packages/beat.core/beat.core-1.13.2.zip/beat.core-1.13.2/beat/core/test/prefix/toolchains/user/loop/1.json
{
    "schema_version": 2,
    "connections": [
        {
            "from": "integers.a",
            "to": "loop_super_block.in",
            "channel": "integers"
        },
        {
            "from": "integers2.out",
            "to": "loop_super_block.in_loop",
            "channel": "integers"
        },
        {
            "from": "loop_super_block.out",
            "to": "analysis.input",
            "channel": "integers"
        },
        {
            "from": "loop_super_block.out_loop",
            "to": "loop_analysis.input",
            "channel": "integers"
        }
    ],
    "datasets": [
        {
            "outputs": [
                "a",
                "b"
            ],
            "name": "integers"
        },
        {
            "outputs": [
                "out"
            ],
            "name": "integers2"
        }
    ],
    "loops": [
        {
            "name": "loop_super_block",
            "synchronized_channel": "integers",
            "processor_inputs": [
                "in"
            ],
            "processor_outputs": [
                "out"
            ],
            "evaluator_inputs": [
                "in_loop"
            ],
            "evaluator_outputs": [
                "out_loop"
            ]
        }
    ],
    "blocks": [
    ],
    "analyzers": [
        {
            "inputs": [
                "input"
            ],
            "synchronized_channel": "integers",
            "name": "analysis"
        },
        {
            "inputs": [
                "input"
            ],
            "synchronized_channel": "integers",
            "name": "loop_analysis"
        }
    ],
    "representation": {
      "connections": {
      },
      "blocks": {
      },
      "channel_colors": {
        "integers": "#5555ff"
      }
    }
}
