=== pypi-data/pypi-mirror-93/packages/beat.core/beat.core-1.13.1.zip/beat.core-1.13.1/beat/core/schema/experiment/1.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Experiment descriptor",
  "description": "This schema defines the properties of a experiment",

  "type": "object",

  "properties": {

    "description": { "$ref": "../common/1.json#/definitions/description" },

    "datasets": {
      "$ref": "common.json#/definitions/datasets"
    },

    "blocks": {
      "$ref": "common.json#/definitions/blocks"
    },

    "analyzers": {
      "$ref": "common.json#/definitions/analyzers"
    },

    "globals": {
      "$ref": "common.json#/definitions/globals"
    },

    "schema_version": { "$ref": "../common/1.json#/definitions/version" }

  },

  "required": [
    "datasets",
    "blocks",
    "analyzers",
    "globals"
  ],

  "additionalProperties": false

}

=== pypi-data/pypi-mirror-93/packages/beat.core/beat.core-1.13.3.zip/beat.core-1.13.3/beat/core/test/prefix/experiments/user/user/double/1/double.json
{
  "analyzers": {
    "analysis": {
      "algorithm": "v1/integers_echo_analyzer/1",
      "inputs": {
        "in_data": "in"
      }
    }
  },
  "blocks": {
    "echo1": {
      "algorithm": "v1/integers_echo/1",
      "inputs": {
        "in_data": "in"
      },
      "outputs": {
        "out_data": "out"
      }
    },
    "echo2": {
      "algorithm": "v1/integers_echo/1",
      "inputs": {
        "in_data": "in"
      },
      "outputs": {
        "out_data": "out"
      }
    }
  },
  "datasets": {
    "set": {
      "database": "simple/1",
      "protocol": "protocol",
      "set": "set"
    }
  },
  "globals": {
    "queue": "queue",
    "environment": {
      "name": "Python for tests",
      "version": "1.3.0"
    }
  }
}

=== pypi-data/pypi-mirror-93/packages/beat.core/beat.core-1.13.2.zip/beat.core-1.13.2/beat/core/test/prefix/experiments/user/user/integers_addition/3/integers_addition.json
{
    "blocks": {
        "addition1": {
            "algorithm": "v1/sum/1",
            "parameters": {
            },
            "inputs": {
                "a": "a",
                "b": "b"
            },
            "outputs": {
                "sum": "sum"
            }
        },
        "addition2": {
            "algorithm": "v1/sum/1",
            "parameters": {
            },
            "inputs": {
                "a": "a",
                "b": "b"
            },
            "outputs": {
                "sum": "sum"
            }
        },
        "addition3": {
            "algorithm": "v1/sum/1",
            "parameters": {
            },
            "inputs": {
                "a": "a",
                "b": "b"
            },
            "outputs": {
                "sum": "sum"
            }
        }
    },
    "datasets": {
        "integers1": {
            "database": "integers_db/1",
            "protocol": "two_sets",
            "set": "double"
        },
        "integers2": {
            "database": "integers_db/1",
            "protocol": "two_sets",
            "set": "triple"
        }
    },
    "analyzers": {
        "analysis": {
            "algorithm": "v1/integers_analysis/1",
            "parameters": {
            },
            "inputs": {
                "input": "input"
            }
        }
    },
    "globals": {
      "environment": {
        "name": "Python for tests",
        "version": "1.3.0"
      },
      "queue": "queue"
    }
}

=== pypi-data/pypi-mirror-93/packages/beat.core/beat.core-1.13.1.zip/beat.core-1.13.1/beat/core/test/prefix/experiments/user/user/integers_addition/2/integers_addition.json
{
    "blocks": {
        "addition1": {
            "algorithm": "v1/sum/1",
            "parameters": {
            },
            "inputs": {
                "a": "a",
                "b": "b"
            },
            "outputs": {
                "sum": "sum"
            }
        },
        "addition2": {
            "algorithm": "v1/sum/1",
            "parameters": {
            },
            "inputs": {
                "a": "a",
                "b": "b"
            },
            "outputs": {
                "sum": "sum"
            }
        }
    },
    "datasets": {
        "integers": {
            "database": "integers_db/1",
            "protocol": "triple",
            "set": "triple"
        }
    },
    "analyzers": {
        "analysis": {
            "algorithm": "v1/integers_analysis/1",
            "parameters": {
            },
            "inputs": {
                "input": "input"
            }
        }
    },
    "globals": {
      "environment": {
        "name": "Python for tests",
        "version": "1.3.0"
      },
      "queue": "queue"
    }
}
