=== pypi-data/pypi-mirror-93/packages/beat.core/beat.core-1.13.1.zip/beat.core-1.13.1/beat/core/schema/experiment/2.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Experiment v2 descriptor",
  "description": "This schema defines the properties of a v2 experiment",

  "type": "object",

  "properties": {

    "description": { "$ref": "../common/1.json#/definitions/description" },

    "datasets": {
      "$ref": "common.json#/definitions/datasets"
    },

    "blocks": {
      "$ref": "common.json#/definitions/blocks"
    },

    "loops": {
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z_][a-zA-Z0-9_-]*$": { "$ref": "#/definitions/loop" }
      },
      "uniqueItems": true,
      "additionalProperties": false
    },

    "analyzers": {
      "$ref": "common.json#/definitions/analyzers"
    },

    "globals": {
      "$ref": "common.json#/definitions/globals"
    },

    "schema_version": { "$ref": "../common/1.json#/definitions/version" }

  },

  "required": [
    "datasets",
    "blocks",
    "analyzers",
    "globals"
  ],

  "additionalProperties": false,

  "definitions": {

    "loop": {
      "type": "object",
      "properties": {
        "processor_algorithm": { "$ref": "../common/1.json#/definitions/reference" },
        "processor_parameters": { "$ref": "common.json#/definitions/parameter_set" },
        "processor_inputs": { "$ref": "common.json#/definitions/connection_map" },
        "processor_outputs": { "$ref": "common.json#/definitions/connection_map" },
        "queue":  { "$ref": "common.json#/definitions/queue" },
        "processor_environment":  { "$ref": "common.json#/definitions/environment" },
        "nb_slots": { "$ref": "common.json#/definitions/slots" },
        "evaluator_algorithm": { "$ref": "../common/1.json#/definitions/reference" },
        "evaluator_parameters": { "$ref": "common.json#/definitions/parameter_set" },
        "evaluator_inputs": { "$ref": "common.json#/definitions/connection_map" },
        "evaluator_outputs": { "$ref": "common.json#/definitions/connection_map" },
        "evaluator_environment":  { "$ref": "common.json#/definitions/environment" }
      },
      "required": [
        "processor_algorithm",
        "processor_inputs",
        "processor_outputs",
        "evaluator_algorithm",
        "evaluator_inputs",
        "evaluator_outputs"
      ],
      "additionalProperties": false
    }

  }

}

=== pypi-data/pypi-mirror-93/packages/beat.core/beat.core-1.13.2.zip/beat.core-1.13.2/beat/core/test/prefix/experiments/user/user/loop/1/with_dash.json
{
    "schema_version": 2,
    "blocks": {
    },
    "loops": {
        "loop_super_block": {
            "processor_algorithm": "user-with_dash/block-with_dash/1",
            "processor_parameters": {
                "step": 1
            },
            "processor_inputs": {
                "in": "in"
            },
            "processor_outputs": {
                "out": "out"
            },

            "evaluator_algorithm": "user/db_input_loop_evaluator/1",
            "evaluator_parameters": {
                "threshold": 9
            },
            "evaluator_inputs": {
                "in_loop": "in_loop"
            },
            "evaluator_outputs": {
                "out_loop": "out_loop"
            }
        }
    },
    "analyzers": {
        "analysis": {
            "algorithm": "v1/integers_analysis/1",
            "parameters": {
            },
            "inputs": {
                "input": "input"
            }
        },
        "loop_analysis": {
            "algorithm": "v1/integers_analysis/1",
            "parameters": {
            },
            "inputs": {
                "input": "input"
            }
        }
    },
    "datasets": {
        "integers": {
            "database": "integers_db/1",
            "protocol": "double",
            "set": "double"
        },
        "integers2": {
            "database": "simple/1",
            "protocol": "protocol2",
            "set": "set"
        }
    },
    "globals": {
        "environment": {
            "name": "Python for tests",
            "version": "1.3.0"
        },
        "queue": "queue",
        "user-with_dash/block-with_dash/1": {
            "step": 2
        },
        "user/db_input_loop_evaluator/1" : {
            "threshold": 8
        }
    }
}
